"""add external_id to users

Revision ID: 4b562524fbff
Revises: 5602b15cb980
Create Date: 2026-04-16 12:09:44.815513

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b562524fbff"
down_revision: str | Sequence[str] | None = "5602b15cb980"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("external_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "external_id")
    # ### end Alembic commands ###
