"""add indexes to transactions

Revision ID: c857812dcc61
Revises: 5602b15cb980
Create Date: 2026-03-24 15:17:57.263413

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c857812dcc61"
down_revision: str | Sequence[str] | None = "5602b15cb980"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_transactions_status_type_payment_date",
        "transactions",
        ["status", "type", "payment_date"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_successful_payment_date",
        "transactions",
        ["payment_date"],
        unique=False,
        postgresql_where=sa.text("status = 'successful'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_transactions_successful_payment_date",
        table_name="transactions",
        postgresql_where=sa.text("status = 'successful'"),
    )
    op.drop_index("ix_transactions_status_type_payment_date", table_name="transactions")
    # ### end Alembic commands ###
